# Generated by Django 4.1.2 on 2022-11-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.CheckConstraint(check=models.Q(('name__regex', '[1-9]'), _negated=True), name='name must not contain any special characters or numbers'),
        ),
        migrations.AlterModelTable(
            name='album',
            table='Albums',
        ),
    ]
